#!/bin/sh

exec 2>&1

# Create directories where couchbase stores its data
cd /opt/couchbase/var
mkdir -p lib/couchbase \
         lib/couchbase/config \
         lib/couchbase/data \
         lib/couchbase/stats \
         lib/couchbase/logs \
         lib/moxi
chgrp -R 0 lib
chmod -R g=u lib
chmod -R g+s lib

exec /opt/couchbase/bin/couchbase-server -- -kernel global_enable_tracing false -noinput
